name: Continuous Integration

on:
  push: # trigger on the push event
    branches:
      - main 
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Select the operating system

    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Specify the Java version
          distribution: 'zulu' # Use Eclipse Temurin distribution
          
      - name: show Java version
        run: "java -version"
        
      - name: Checkout code
        uses: actions/checkout@v4 # Clone the project.
          
      - name: Show directory
        run: 'pwd'
        
      - name: List files
        run: 'ls -al'
          
      - name: Install dependencies 
        run: 'mvn compile' #  Install dependencies
        
      - name: Build the app # Create a project build.
        run: 'mvn package -DskipTest'

      - name: Run tests # Run unit tests.
        run: 'mvn test'
